apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: newapp-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/newapp/overlays/production/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

