apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: newapp-app
  namespace: flux-system
spec:
  interval: 1m
  dependsOn: 
    - name: namespaces
  path: ./apps/newapp/overlays/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

