apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tester
  namespace: flux-system
spec:
  interval: 1m
  path: ./tester
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

