apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tester-app
  namespace: flux-system
spec:
  interval: 1m
  dependsOn: namespaces
  path: ./apps/tester/overlays/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

